#!/usr/bin/env bash

if [[ $# == 0 ]]; then
	echo "labpath is required"
	exit 1
fi;

LAB_PATH=$1
shift

docker build -t test-shell-runner -f Dockerfile .
docker run --rm -v $LAB_PATH:/shell/lab-to-test test-shell-runner make test
