#!/usr/bin/env bash

set -eu

FORK_TEST_DIR=$1

# compile the project
cd $FORK_TEST_DIR
make clean
make
cd ..

# run the tests
./find-test.py "./$FORK_TEST_DIR/find"
./pingpong-test.py "./$FORK_TEST_DIR/pingpong"
./xargs-test.py "./$FORK_TEST_DIR/xargs"
